# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170905_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='dignose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='entdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='hospitno_fk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='outdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='patid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PatientInfo'),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='patid_fk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='patid_fk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='sex',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
