# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170905_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalizationinfo',
            name='doctor',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='blog.Profile'),
        ),
    ]
