# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_barthel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_time', models.DateTimeField(null=True)),
                ('conservative_treatment', models.NullBooleanField()),
                ('first_recover_care', models.NullBooleanField()),
                ('diabetes', models.NullBooleanField()),
                ('hypertension', models.NullBooleanField()),
                ('smoke', models.NullBooleanField()),
                ('drink', models.NullBooleanField()),
                ('hospid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.HospitalizationInfo')),
            ],
        ),
    ]
