# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_medhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistory',
            name='createtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medhistory',
            name='dignose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medhistory',
            name='glu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medhistory',
            name='ldl_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medhistory',
            name='tg',
            field=models.IntegerField(null=True),
        ),
    ]
