# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170922_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('prob_improve', models.IntegerField(null=True)),
                ('hospid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.HospitalizationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResultFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_high', models.IntegerField(null=True)),
                ('ci_low', models.IntegerField(null=True)),
                ('factor_name', models.IntegerField(null=True)),
                ('is_positive', models.IntegerField(null=True)),
                ('odds_ratio', models.IntegerField(null=True)),
                ('p_value', models.IntegerField(null=True)),
                ('model_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ModelResult')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
