# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170928_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='prob_improve',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='ci_high',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='ci_low',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='factor_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='is_positive',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='odds_ratio',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelresultfactor',
            name='p_value',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
