# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171010_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barthel',
            name='rater',
        ),
    ]
