# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_barthel_rater'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=50, null=True)),
                ('character', models.CharField(max_length=200, null=True)),
                ('group_id', models.CharField(max_length=50, null=True)),
                ('patient_num', models.FloatField(max_length=20, null=True)),
                ('sex_man', models.FloatField(max_length=20, null=True)),
                ('first_recover_care', models.FloatField(max_length=20, null=True)),
                ('hypertension', models.FloatField(max_length=20, null=True)),
                ('diabetes', models.FloatField(max_length=20, null=True)),
                ('conservative_treatment', models.FloatField(max_length=20, null=True)),
                ('stroke_2', models.FloatField(max_length=20, null=True)),
                ('age', models.FloatField(max_length=20, null=True)),
                ('enter_barthel', models.FloatField(max_length=20, null=True)),
                ('stroke_time', models.FloatField(max_length=20, null=True)),
                ('glu', models.FloatField(max_length=20, null=True)),
                ('tg', models.FloatField(max_length=20, null=True)),
                ('ldl_c', models.FloatField(max_length=20, null=True)),
                ('qiya', models.FloatField(max_length=20, null=True)),
                ('dianzi', models.FloatField(max_length=20, null=True)),
                ('yanyu', models.FloatField(max_length=20, null=True)),
                ('xiazhi', models.FloatField(max_length=20, null=True)),
                ('tunyan', models.FloatField(max_length=20, null=True)),
                ('zuoye', models.FloatField(max_length=20, null=True)),
                ('liliao', models.FloatField(max_length=20, null=True)),
                ('other_treatment', models.FloatField(max_length=20, null=True)),
                ('imporve', models.FloatField(max_length=20, null=True)),
                ('qiya_effect', models.NullBooleanField()),
                ('dianzi_effect', models.NullBooleanField()),
                ('yanyu_effect', models.NullBooleanField()),
                ('xiazhi_effect', models.NullBooleanField()),
                ('tunyan_effect', models.NullBooleanField()),
                ('zuoye_effect', models.NullBooleanField()),
                ('liliao_effect', models.NullBooleanField()),
                ('other_treatment_effect', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='hospitalizationinfo',
            name='similarity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
