# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171017_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similaritygroup',
            old_name='character',
            new_name='group_character',
        ),
    ]
