# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171017_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medhistory',
            name='glu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='ldl_c',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='tg',
            field=models.FloatField(null=True),
        ),
    ]
