# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171019_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritygroup',
            name='recommend_treat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
